# Generated by Django 2.2.28 on 2022-05-03 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_paypal', '0003_auto_20200124_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='paypalpayment',
            name='related_resource_state',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='related resource state'),
        ),
    ]
