# Generated by Django 2.2.28 on 2024-04-23 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_paypal', '0005_auto_20240207_0630'),
    ]

    operations = [
        migrations.AddField(
            model_name='paypalwebhook',
            name='auth_hash',
            field=models.CharField(default='', max_length=255, unique=True, verbose_name='Auth Hash'),
        ),
    ]
